neaten.var.names<-function(relinftbl){
  relinftbl[which(relinftbl$var=="TCrange"),1]="TC range"
  relinftbl[which(relinftbl$var=="TempRange"),1]="TR"
  relinftbl[which(relinftbl$var=="LCT_15"),1]="LCT 15"
  relinftbl[which(relinftbl$var=="Rug2"),1]="Rug"
  relinftbl[which(relinftbl$var=="prcp..mm.day."),1]="Prcp"
  relinftbl[which(relinftbl$var=="temprangeRange"),1]="TR range"
  relinftbl[which(relinftbl$var=="tmaxrange"),1]="Tmax range"
  relinftbl[which(relinftbl$var=="prcprange"),1]="Prcp range"
  relinftbl[which(relinftbl$var=="Mastsums"),1]="Mast sums"
  relinftbl[which(relinftbl$var=="LCT_17"),1]="LCT 17"
  relinftbl[which(relinftbl$var=="LCT_14"),1]="LCT 14"
  relinftbl[which(relinftbl$var=="LCT_8"),1]="LCT 8"
  relinftbl[which(relinftbl$var=="LCT_10"),1]="LCT 10"
  relinftbl[which(relinftbl$var=="LCT_5"),1]="LCT 5"
  relinftbl[which(relinftbl$var=="dayl..s."),1]="daylight"
  relinftbl[which(relinftbl$var=="LCsums"),1]="LCT sums"
  relinftbl[which(relinftbl$var=="Mast_4"),1]="Mast 4"
  relinftbl[which(relinftbl$var=="Rug2range"),1]="Rug range"
  relinftbl[which(relinftbl$var=="LCT_6"),1]="LCT 6"
  relinftbl[which(relinftbl$var=="LCT_1"),1]="LCT 1"
  relinftbl[which(relinftbl$var=="tmin..deg.c."),1]="Tmin"
  relinftbl[which(relinftbl$var=="tminrange"),1]="Tmin range"
  relinftbl[which(relinftbl$var=="Droughtrange"),1]="Drought range"
  relinftbl[which(relinftbl$var=="tmax..deg.c."),1]="Tmax"
  relinftbl[which(relinftbl$var=="LCT_7"),1]="LCT 7"
  relinftbl[which(relinftbl$var=="Mast_17"),1]="Mast 17"
  relinftbl[which(relinftbl$var=="PRd2"),1]="Prox rd"
  relinftbl[which(relinftbl$var=="Prd2range"),1]="Prox rd range"
  relinftbl[which(relinftbl$var=="LCT_18"),1]="LCT 18"
  relinftbl[which(relinftbl$var=="LCT_16"),1]="LCT 16"
  relinftbl[which(relinftbl$var=="Mast_8"),1]="Mast 8"
  relinftbl[which(relinftbl$var=="Mast_3"),1]="Mast 3"
  relinftbl[which(relinftbl$var=="Mast_18"),1]="Mast 18"
  relinftbl[which(relinftbl$var=="Mast_1"),1]="Mast 1"
  relinftbl[which(relinftbl$var=="LCT_3"),1]="LCT 3"
  relinftbl[which(relinftbl$var=="Mast_7"),1]="Mast 7"
  relinftbl[which(relinftbl$var=="Mast_19"),1]="Mast 19"
  relinftbl[which(relinftbl$var=="Mast_2"),1]="Mast 2"
  relinftbl[which(relinftbl$var=="Mast_13"),1]="Mast 13"
  relinftbl[which(relinftbl$var=="LCT_9"),1]="LCT 9"
  relinftbl[which(relinftbl$var=="Mast_5"),1]="Mast 5"
  relinftbl[which(relinftbl$var=="Mast_6"),1]="Mast 6"
  relinftbl[which(relinftbl$var=="LCT_4"),1]="LCT 4"
  relinftbl[which(relinftbl$var=="Mast_16"),1]="Mast 16"
  relinftbl[which(relinftbl$var=="Mast_0"),1]="Mast 0"
  relinftbl[which(relinftbl$var=="Mast_9"),1]="Mast 9"
  relinftbl[which(relinftbl$var=="Mast_10"),1]="Mast 10"
  relinftbl[which(relinftbl$var=="Mast_11"),1]="Mast 11"
  relinftbl[which(relinftbl$var=="Mast_12"),1]="Mast 12"
  relinftbl[which(relinftbl$var=="Mast_14"),1]="Mast 14"
  relinftbl[which(relinftbl$var=="Mast_15"),1]="Mast 15"
  relinftbl[which(relinftbl$var=="Mast_20"),1]="Mast 20"
  relinftbl[which(relinftbl$var=="Mast_21"),1]="Mast 21"
  return(relinftbl)
}

neaten.var.names.full<-function(relinftbl){
  relinftbl[which(relinftbl$var=="TCrange"),1]="Tree cover range"
  relinftbl[which(relinftbl$var=="TempRange"),1]="Temp. Range"
  relinftbl[which(relinftbl$var=="LCT_1"),1]="Prop. LC 1"
  relinftbl[which(relinftbl$var=="LCT_3"),1]="Prop. LC 3"
  relinftbl[which(relinftbl$var=="LCT_4"),1]="Prop. LC 4"
  relinftbl[which(relinftbl$var=="LCT_5"),1]="Prop. LC 5"
  relinftbl[which(relinftbl$var=="LCT_6"),1]="Prop. LC 6"
  relinftbl[which(relinftbl$var=="LCT_7"),1]="Prop. LC 7"
  relinftbl[which(relinftbl$var=="LCT_8"),1]="Prop. LC 8"
  relinftbl[which(relinftbl$var=="LCT_9"),1]="Prop. LC 9"
  relinftbl[which(relinftbl$var=="LCT_10"),1]="Prop. LC 10"
  relinftbl[which(relinftbl$var=="LCT_14"),1]="Prop. LC 14"
  relinftbl[which(relinftbl$var=="LCT_15"),1]="Prop. LC 15"
  relinftbl[which(relinftbl$var=="LCT_16"),1]="Prop. LC 16"
  relinftbl[which(relinftbl$var=="LCT_17"),1]="Prop. LC 17"
  relinftbl[which(relinftbl$var=="LCT_18"),1]="Prop. LC 18"
  relinftbl[which(relinftbl$var=="Rug2"),1]="Ruggedness"
  relinftbl[which(relinftbl$var=="prcp..mm.day."),1]="Precip."
  relinftbl[which(relinftbl$var=="daylrange"),1]="Daylight range"
  relinftbl[which(relinftbl$var=="tmaxrange"),1]="Tmax range"
  relinftbl[which(relinftbl$var=="tminrange"),1]="Tmin range"
  relinftbl[which(relinftbl$var=="prcprange"),1]="Precip. range"
  relinftbl[which(relinftbl$var=="Mastrange"),1]="Mast range"
  relinftbl[which(relinftbl$var=="dayl..s."),1]="Daylight"
  relinftbl[which(relinftbl$var=="LCsums"),1]="Number land classes"
  relinftbl[which(relinftbl$var=="Rug2range"),1]="Ruggedness range"
  relinftbl[which(relinftbl$var=="tmin..deg.c."),1]="Tmin"
  relinftbl[which(relinftbl$var=="tminrange"),1]="Tmin range"
  relinftbl[which(relinftbl$var=="Droughtrange"),1]="Drought range"
  relinftbl[which(relinftbl$var=="tmax..deg.c."),1]="Tmax"
  relinftbl[which(relinftbl$var=="PRd2"),1]="Proximity rd."
  relinftbl[which(relinftbl$var=="Prd2range"),1]="Proximity rd. range"
  return(relinftbl)
}